version: '3'

services:
  maria_db:
    container_name: maria_db
    image: szymonzieba/no-injection-lxo:mariadb
    ports:
      - 127.0.0.1:3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: "admin"
      MARIADB_DATABASE: "mysql"
      MARIADB_USER: "admin@test.pl"
      MARIADB_PASSWORD: "admin"
    tty: true

  node_server:
    container_name: node_server
    image: szymonzieba/no-injection-lxo:node
    depends_on: 
      - maria_db
    volumes: 
      - './:/app'
    ports:
      - 3000:3000
    environment:
      DB_HOST: 'maria_db'
    command: >
      bash -c "cd /app
      && npm install 
      && npm run start"
    tty: true